UCLALibrary/docker-cantaloupe

.gitignore
Dockerfile
README.md

Utilizing a multi-stage build, the first stage either downloads the release .zip file for Cantaloupe, or the current version of the source code, and then the build stage compiles Cantaloupe with Maven if the requested version = latest. The remainder of the build remains the same.

[IIIF-2] build canteloupe from source

---

Dockerfile
README.md

We want to have the option to build against the latest developer snapshot. Sometimes this breaks though, so we need a way to defensively build the "last known good commit". This PR adds a `LATEST_SAFE_COMMIT` build argument. By default it's set for "latest" (which assumes a working Cantaloupe build), but it can be changed to a particular git commit hash to use that version of the code when building. This new argument is also documented in the README now.
The new argument only comes into play if someone is building CANTALOUPE_VERSION=latest. Otherwise, it's ignored.

Add defensive measures against broken upstream

---

.travis.yml
.travis/deploy.sh
.travis/upgrade.sh
tests/run-locally.sh
tests/run-tests.sh
tests/validate-results.sh

We want to push a versioned artifact from each build (right now just stable releases and a dev snapshot) up into DockerHub. We do the build for each and then deploy it to DockerHub where we can later pull it down for use. The tests here are just placeholders for IIIF-23, but are needed to show that we're going through testing before we're pushing something into the registry.

Update Travis config to use push versioned artifacts to DockerHub

---

spec/dev/cantaloupe_dev_spec.rb

Parameterize COMMIT_REF so it's not hard coded. Upstream seems fixed now anyway though since your PR was merged, @hardyoyo

Parameterize commit_ref

---

.travis.yml
Dockerfile

We're bumping into Travis' log limit (at which point they kill the job) so we need to reduce the unnecessary output in our build. This PR makes Maven and Curl a little quieter.

Make build a little quieter

---

.travis.yml
.travis/deploy.sh
Dockerfile
cantaloupe.properties.default
spec/cantaloupe_spec.rb

* Fix the openjpeg tools path in the Cantaloupe default config
* Change to using Ubuntu base image to get the latest OpenJPEG library that we need to work with S3
* Remove COMMIT_REF now that Cantaloupe build is fixed
* Move deploy debugging around a little to get more information, earlier
* Add two more tests

Iiif 59 fix openjpeg path

---

Dockerfile
Rakefile
spec/Dockerfile.erb
spec/cantaloupe_spec.rb
spec/spec_helper.rb

Fixes [IIIF-55]
Also fixes a bug ([IIIF-70]) that went unnoticed previously because the build output was so voluminous (and Travis failed to fail the build when it happened).

Reduce unnecessary build output

---

.travis.yml

Move the location of the COMMIT_REF optional build argument to be in the Travis UI settings rather than in the .travis.yml file (which requires commits to change).

[IIIF-57] Move commit_ref to UI settings

---

README.md

Travis moved our project from .org to .com so we need to update the badge links (since builds are no longer happening at the .org address).

Update Travis links in badge

---

.travis.yml

Turn on builds on branches and PRs in the Travis config but only specify building on master branch in the Travis config _should_ give us builds on all PRs but only on 'master' branch?
https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda

Only do Travis builds on master branch (and PRs)

---

Dockerfile

Based on the excellent suggestion from Codacy, I have dropped our two instances of cd commands in our Dockerfile and am instead using a WORKDIR setting. This should be safer and more clear.

[IIIF-73] Use WORKDIR instead of cd

---

Dockerfile

Set the output path for the curl command that downloads cantaloupe, so it goes into the folder we expect it to.

[IIIF-87] Set the output path for the cantaloupe download curl command

---

spec/spec_helper.rb

- add fail-if-no-example to the spec_helper.rb config for rspec

[IIIF-88] set fail-if-no-example in spec_helper.rb

---

spec/spec_helper.rb

- Add fail-fast option, so a single test failure fails the build immediately

[IIIF-89] Add fail-fast option to rspec.config in spec_helper.rb

---

.snyk
Dockerfile
spec/cantaloupe_spec.rb

- changes the base image for Ubuntu from 18.4 LTS to 18.10
- changes all pinned package versions to match what is provided by 18.10
- changes all tests to confirm new package version numbers
- adds a .snyk file to ignore two vulernable gem packages, from DockerSpec, because we do not deploy these gems, we just use DockerSpec for testing

[IIIF-76] Address concerns raised by Snyk by moving to Ubuntu 18.10 as a base image

---

Dockerfile
configs/cantaloupe.properties.default-4.1.2
configs/cantaloupe.properties.tmpl-4.1.2
spec/cantaloupe_spec.rb

Unfortunately, using a standard template for 4.x.x configs in the Dockerfile is more difficult than I thought. Due to the nature of using Dockerfile's COPY command to copy the cantaloupe configs into place, we can't manipulate Docker ENVs as easily. 
I'm aware of how to do this in bash pretty easily. Docker ENV's are pretty explicit strings and can't be parsed with regex. From my perspective, it seems that we'd have to control versioning at a higher level than the Dockerfile or get away from using Docker's COPY to make this work.

[IIIF-188] optimize docker build

---

Dockerfile

I found libturbojpeg was missing when running using a volume holding jpg images.
Fixed this and also added some copying in order to make jni work.

missing libturbojpeg

---

README.md
configs/cantaloupe.properties.default-4.0.2
configs/cantaloupe.properties.default-4.0.3
configs/cantaloupe.properties.default-4.1
configs/cantaloupe.properties.default-4.1.1
configs/cantaloupe.properties.default-4.1.2
configs/cantaloupe.properties.default-dev

We use `/imageroot/` in our documentation for the images mount inside the container, but we don't provide sane defaults in our configs for that. Update configs to use `/imagesroot/` (can always be overridden).

Update default config source fs path

---

Dockerfile
README.md
spec/cantaloupe_spec.rb

* Set default version of Cantaloupe to 4.1.2 for the stable build
* revise spec for stable build to verify version 4.1.2 is deployed
* Pin libturbojpeg
* revise spec to confirm the pinned version of libturbojpeg is installed

[IIIF-316] Set Cantaloupe to 4.1.2 and pin libturbo

---

.travis.yml
Dockerfile
docker-entrypoint.sh
spec/Dockerfile.erb
spec/cantaloupe_spec.rb

* Add a download of a delegate script to the docker-entrypoint.sh script for docker-cantaloupe
* This delegate script download is triggered by the presence of a DELEGATE_URL ENV variable
* This DELEGATE_URL ENV variable is passed a URL in our DockerSpec tests to confirm that it works

[IIIF-424] Add capacity to include a delegate script into docker-cantaloupe

---

.travis/trigger-docker-build.sh
Jenkinsfile

The current travis.yml setup is set to matrix off jobs. Meaning each run will cause a trigger to our Jenkins cantaloupe-ucla build. I'm currently setting a place holder to only have the stable job trigger the job.
Long term, we may we want to move this to the TravisCI jobs pipeline that bucketeer is using.

[IIIF-490] Temporary fix to remove multiple triggers

---

.rubocop.yml
Dockerfile
configs/cantaloupe.properties.default-4.1.5
configs/cantaloupe.properties.tmpl-4.1.5
spec/Dockerfile.erb
spec/cantaloupe_spec.rb

* Upgrade Cantaloupe (fixes CVEs)
* Update LineLength package for rubocop
* Update Ubuntu version
* Update distro packages from Ubuntu
* Removed version pinning in Dockerfile.erb since that's the Dockerfile that we use to build our test image (and it's not published anywhere)
* Update tests to check for new version numbers

[IIIF-821] Update to fix security issues

---

src/main/docker/docker-entrypoint.sh

Please review the full file to see the new changes. The reason we're adding jars directly into the jar/war file via entrypoint and not maven is because we don't control the pom file. That's pulled from upstream Cantaloupe.
It also turns out that Cantaloupe upstream overrides the log4j libraries with Joran libs. Meaning we can't just pass in an external logback config through parameters because Joran overrides it. We would have to modify the upstream code to resolve that issue.

[IIIF-838] Make custom logback handle both jar and war files

---

.travis.yml

We want to run the dev builds (on the 5.x line) only as nightly cron jobs.

[IIIF-916] Skip devBuilds except on cron

---

pom.xml
src/main/docker/Dockerfile
src/main/docker/configs/cantaloupe.properties.default-4.1.5
src/main/docker/configs/cantaloupe.properties.tmpl-4.1.5

Fluency integration wasn't working due to missing zip package. Solution was to add zip to be installed via pom and Dockerfile. Due to 4.1.6 bug with Kakadu outputting truncated log errors, I've reverted the build to 4.1.5. Two following commits/PRs will be created after this to build 4.1.5-1 and set up the next build for 4.1.6-2-SNAPSHOT

[IIIF-936] Add 4.1.5 build and fix fluency integration
